# https://github.com/peaceiris/actions-gh-pages
name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    concurrency: # https://docs.github.com/ja/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-node@v3
        with:
          node-version: 16

      - name: Build
        working-directory: ./
        run: |
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
